export const MOCK_MEMES = [
    {
        id: "1",
        title: "When the code finally works on the first try",
        category: "Coding",
        thumbnail: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=1000&auto=format&fit=crop",
        videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-working-on-his-laptop-308-large.mp4",
        duration: "0:05",
        creator: {
            name: "TechLead",
            avatar: "https://i.pravatar.cc/150?u=techlead",
        },
        views: "1.2M",
        timePosted: "2h ago",
        trendingScore: 98,
    },
    {
        id: "2",
        title: "Pov: You forgot to push before leaving",
        category: "Work Life",
        thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1000&auto=format&fit=crop",
        duration: "0:12",
        creator: {
            name: "JuniorDev",
            avatar: "https://i.pravatar.cc/150?u=juniordev",
        },
        views: "850K",
        timePosted: "4h ago",
        trendingScore: 92,
    },
    {
        id: "3",
        title: "AI taking over my job like...",
        category: "AI",
        thumbnail: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1000&auto=format&fit=crop",
        videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-futuristic-robot-head-interface-3051-large.mp4",
        duration: "0:08",
        creator: {
            name: "FutureProof",
            avatar: "https://i.pravatar.cc/150?u=futureproof",
        },
        views: "2.1M",
        timePosted: "1h ago",
        trendingScore: 99,
    },
    {
        id: "4",
        title: "Deploying on Friday",
        category: "Coding",
        thumbnail: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=1000&auto=format&fit=crop",
        videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-programmer-coding-on-computer-in-office-34444-large.mp4",
        duration: "0:15",
        creator: {
            name: "SeniorDev",
            avatar: "https://i.pravatar.cc/150?u=seniordev",
        },
        views: "500K",
        timePosted: "6h ago",
        trendingScore: 85,
    },
    {
        id: "5",
        title: "React Hooks explained by a cat",
        category: "Education",
        thumbnail: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=1000&auto=format&fit=crop",
        videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-kitten-playing-with-a-toy-on-the-bed-43445-large.mp4",
        duration: "0:30",
        creator: {
            name: "CatCoder",
            avatar: "https://i.pravatar.cc/150?u=catcoder",
        },
        views: "3.5M",
        timePosted: "12h ago",
        trendingScore: 95,
    },
];

export const CATEGORIES = [
    "All",
    "Trending",
    "Coding",
    "AI",
    "Gaming",
    "Reactions",
    "Pets",
    "News",
];
